name = "FFTInterpolate"
uuid = "1ef05b6e-51a9-4259-aab2-3b44731d040d"
authors = ["Caleb Jacobs <calebjacobs210@gmail.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[compat]
FFTW = "1.8.0"
