name = "ComplexVisuals"
uuid = "a4eac8e2-b850-4e34-bd58-e2db9627dab1"
authors = ["Caleb Jacobs <calebjacobs210@gmail.com>"]
version = "0.1.0"

[deps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"

[compat]
Makie = "0.21.18"
MakieCore = "0.8.12"
