name = "ComplexVisualsMakie"
uuid = "ec2e7517-96cc-4a5f-9dfe-ddb9c3fb2531"
authors = ["Caleb Jacobs <calebjacobs210@gmail.com>"]
version = "0.1.0"

[deps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"

[compat]
Makie = "0.21.15"
MakieCore = "0.8.9"
